# filepath: /Users/yinray/Documents/workspace-mac/rag-sample-mistral/Mistral_transformers_pipeline_starter/Dockerfile
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "scripts/mistral_starter_chat.py"]